from backend.attachments.validators import validate_attachment, SUPPORTED_DOCUMENT_TYPES, SUPPORTED_IMAGE_TYPES
from backend.attachments.storage import save_file, move_attachments_to_conversation, get_absolute_path
from backend.attachments.extractors import extract_text, ExtractionError
